# THIS FILE IS MANAGED BY THE CONTAINER AND REPLACED ON STARTUP.
# DO NOT EDIT THIS FILE - ANY CHANGES WILL BE LOST.
# TO ADD YOUR OWN CONFIGURATION, USE: *.local FILE.

# Load base dockerfile env variables
if [[ -f "/etc/jdvm-templates/base/dockerfile-env" ]]; then
  source "/etc/jdvm-templates/base/dockerfile-env"
fi
# Load base env variables
if [[ -f "/etc/jdvm-templates/base/env" ]]; then
  source "/etc/jdvm-templates/base/env"
fi
# Load env variables
if [[ -f "${HOME}/.env" ]]; then
  source "${HOME}/.env"
fi
# Load base docker env variables
if [[ -f "/etc/jdvm-templates/base/docker-env" ]]; then
  source "/etc/jdvm-templates/base/docker-env"
fi
# Load user-specific env variables
if [[ -f "${HOME}/.env.local" ]]; then
  source "${HOME}/.env.local"
fi
if [[ -f "${HOME}/.zshenv.local" ]]; then
  source "${HOME}/.zshenv.local"
fi
